language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl libreadline-dev libboost-all-dev
  - git clone https://github.com/skystrife/cpptoml && cd cpptoml && mkdir build && cd build && cmake .. && make && sudo make install && cd ../..
script:
  - mkdir build && cd build 
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=ON .. 
  - make 
  - make coveralls 
  - make test
