language: cpp
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq libreadline-dev
  - git clone https://github.com/skystrife/cpptoml && cd cpptoml && mkdir build && cd build && cmake .. && make && make install
script:
  - mkdir build && cd build && cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && cmake --build . --target coveralls
